import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.BailErrorStrategy;

// Our parser extends the base visitor generated by ANTLR
public class Hello extends HelloBaseVisitor<String> {

	// We override all visitXXX methods

	@Override
	public String visitStart(HelloParser.StartContext ctx) {
		return ctx.name.getText(); //this.visit(ctx.name());
	}

	public static void main(String args[]) throws Exception {

		while (true) {

			// read an expression from the console
			System.out.println("Who are you?");
			String input = System.console().readLine();

			// build the parser for the content of the input
			HelloLexer lex = new HelloLexer(new ANTLRInputStream(input));
			CommonTokenStream tokens = new CommonTokenStream(lex);
			HelloParser parser = new HelloParser(tokens);
			parser.setErrorHandler(new BailErrorStrategy());

			// print the result of parsing the input
			Hello myHello = new Hello();
			try {
				String name = myHello.visit(parser.start());
				System.out.println("Hello " + name + "!");
			}
			catch (Exception e){
			}

		}
	}

}
