import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

// Our calculator extends the base visitor generated by ANTLR
public class Calculator extends CalculatorBaseVisitor<Double> {

	// We override all visitXXX methods

	@Override
	public Double visitStart(CalculatorParser.StartContext ctx) {
		return this.visit(ctx.expr());
	}

	@Override
	public Double visitTimesExpr(CalculatorParser.TimesExprContext ctx) {
		// recursively visit/evaluate twe two operands
		return (visit(ctx.lhs) * visit(ctx.rhs));
	}

	@Override
	public Double visitDivExpr(CalculatorParser.DivExprContext ctx) {
		// recursively visit/evaluate twe two operands
		return (visit(ctx.lhs) * visit(ctx.rhs));
	}

	@Override
	public Double visitPlusExpr(CalculatorParser.PlusExprContext ctx) {
		// recursively visit/evaluate twe two operands
		return (visit(ctx.lhs) + visit(ctx.rhs));
	}


	@Override
	public Double visitMinusExpr(CalculatorParser.MinusExprContext ctx) {
		// recursively visit/evaluate twe two operands
		return (visit(ctx.lhs) - visit(ctx.rhs));
	}

	@Override
	public Double visitPowExpr(CalculatorParser.PowExprContext ctx) {
		// recursively visit/evaluate twe two operands
		return (Math.pow(visit(ctx.lhs),visit(ctx.rhs)));
	}

	@Override
	public Double visitNumExpr(CalculatorParser.NumExprContext ctx) {
		return Double.valueOf(ctx.getText());
	}

	@Override
	public Double visitNestedExpr(CalculatorParser.NestedExprContext ctx) {
		return this.visit(ctx.expr());
	}

	public static void main(String args[]) throws Exception {

		while (true) {

			// read an expression from the console
			System.out.print("Enter an arithmetic expression: ");
			String input = System.console().readLine();

			// build the parser for the content of the input
			CharStream inputStream = CharStreams.fromString(input);
			CalculatorLexer lex = new CalculatorLexer(inputStream);
			CommonTokenStream tokens = new CommonTokenStream(lex);
			CalculatorParser parser = new CalculatorParser(tokens);

			// print the result of parsing the input
			Calculator myCalc = new Calculator();
			System.out.println(myCalc.visit(parser.start()));

		}
	}

}
